AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ECSClusterName:
    Type: String
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ECSClusterName
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 1
      Configuration:
        ExecuteCommandConfiguration:
          Logging: DEFAULT
      Tags:
        - Key: Application
          Value: NodeApp
Outputs:
  ECSCluster:
    Description: Name od the ECS cluster
    Value: !GetAtt 'ECSCluster.Arn'
    Export:
      Name: node-ecs-cluster
