AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ECSTaskRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub ECSTask-Role-${AWS::AccountId}-${AWS::Region}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - 'sts:AssumeRole'     
          - Effect: Allow
            Principal:
              Service:
                - ecs.application-autoscaling.amazonaws.com
            Action:
              - 'sts:AssumeRole'                       
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
  ECSExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub ECSExecution-Role-${AWS::AccountId}-${AWS::Region}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - 'sts:AssumeRole'     
          - Effect: Allow
            Principal:
              Service:
                - ecs.application-autoscaling.amazonaws.com
            Action:
              - 'sts:AssumeRole'                       
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole
        - arn:aws:iam::aws:policy/CloudWatchFullAccess        
